language: generic 
sudo: required #super user permission
services:
  - docker

before_install:
  - docker build -t  Mrchanghao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Mrchanghao/docker-react npm run test  

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-108390507437"
  bucket_path: "docker-react" # app name 과 같음
  on:
    branch: master
