sudo: required #super user permission
services:
  - docker

before_install:
  - docker build -t  Mrchanghao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Mrchanghao/docker-react npm run test